
default_platform(:ios)

platform :ios do
  
  desc "Sumbit app to App Store"
  lane :release do
    sync_certificates
    build_ipa
    snapshot
    deliver
  end
    
  desc "Package and submit a new version to TestFlight"
  lane :beta do
    # Create/Update the certificates
    sync_certificates

    # Increment the build number
    increment_build_number

    # Build your app - more options available
    gym

    # Upload to TestFlight
    pilot(
      username: "#{ENV['APPLE_DEVELOPER_EMAIL']}",
      team_name: "#{ENV['APPLE_DEVELOPER_TEAM_NAME']}",
    )
  end

  desc "Create/Update the certificates"
  lane :sync_certificates do 
    # ENVIRONMENT: [development, appstore, adhoc, enterprise]
    match(type: "#{ENV['ENVIRONMENT']}", readonly: false)
  end

  desc "Builds an .ipa file of the app"
  lane :build_ipa do
    # Increase the build number by 1
    increment_build_number
    # Creates a signed file
    gym(xcargs: "-allowProvisioningUpdates")
  end

  desc "Build bundler identifier"
  lane :build_bundle_identifier do
    produce(
    username: "#{ENV['APPLE_DEVELOPER_EMAIL']}",
    app_identifier: "#{ENV['APP_IDENTIFIER']}",
    app_name: 'Random MTG',
    language: "English",
    app_version: "1.0",
    # sku: '123',
    team_name: "#{ENV['APPLE_DEVELOPER_TEAM_NAME']}", # only necessary when in multiple teams
    itc_team_name: "#{ENV['APPLE_DEVELOPER_TEAM_NAME']}", # only necessary when in multiple teams,

    # Optional
    # App services can be enabled during app creation
    enable_services: {
      access_wifi: "on",                        # Valid values: "on", "off"
      auto_fill_credential: "on",               # Valid values: "on", "off"
      custom_network_protocol: "on",            # Valid values: "on", "off"
      in_app_purchase: "on",                    # Valid values: "on", "off"
      network_extension: "on",                  # Valid values: "on", "off"
    }
  )
  end
end
