
default_platform(:ios)

platform :ios do
  
  desc "Sumbit app to App Store"
  lane: release do
    sync_certificates
    build_ipa
    snapshot
    deliver
  end
    
  desc "Package and submit a new version to TestFlight"
  lane :beta do
    # Create/Update the certificates
    sync_certificates

    # Increment the build number
    increment_build_number

    # Build your app - more options available
    gym

    # Upload to TestFlight
    pilot(
      username: "#{ENV['APPLE_DEVELOPER_EMAIL']}",
      team_name: "#{ENV['APPLE_DEVELOPER_TEAM_NAME']}",
    )
  end

  desc "Create/Update the certificates"
  lane :sync_certificates do 
    # ENVIRONMENT: [development, appstore, adhoc, enterprise]
    match(type: "#{ENV['ENVIRONMENT']}", readonly: true)
  end

  desc "Builds an .ipa file of the app"
  lane :build_ipa do
    # Increase the build number by 1
    increment_build_number
    # Creates a signed file
    gym(xcargs: "-allowProvisioningUpdates")
  end

end
